#!/usr/bin/env -S deno run --allow-read --allow-write

/**
 * Embeds taglib.wasm as base64 in a TypeScript file for compiled binaries.
 */

import { encode } from "jsr:@std/encoding/base64";

const WASM_PATH = "./taglib.wasm";
const OUTPUT_PATH = "./src/lib/taglib_wasm_data.ts";

console.log("Embedding taglib.wasm as base64...");

try {
  const wasmData = await Deno.readFile(WASM_PATH);
  const base64Data = encode(wasmData);

  const tsContent = `// Auto-generated file. Do not edit.
// Generated by scripts/embed_wasm.ts

export const TAGLIB_WASM_BASE64 = "${base64Data}";
`;

  await Deno.writeTextFile(OUTPUT_PATH, tsContent);

  console.log(`✓ Embedded taglib.wasm (${wasmData.length} bytes)`);
  console.log(`✓ Saved to ${OUTPUT_PATH}`);
} catch (error) {
  console.error("Failed to embed taglib.wasm:", error);
  Deno.exit(1);
}
